Bugfix: Gem::InvalidSpecificationException
Specification "files"

   "
   Directories are automatically stripped from this list when
   building a gem, other non-files cause an error.
   "
   See more at https://guides.rubygems.org/specification-reference/#files

Stack error
===

bundle exec rake release
rake aborted!
Running `gem build -V /app/moltrio-config.gemspec` failed with the following output:

WARNING:  See https://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    [".gitignore"] are not files

/usr/local/bundle/gems/bundler-2.3.12/lib/bundler/gem_helper.rb:211:in `sh'
/usr/local/bundle/gems/bundler-2.3.12/lib/bundler/gem_helper.rb:88:in `build_gem'
/usr/local/bundle/gems/bundler-2.3.12/lib/bundler/gem_helper.rb:47:in `block in install'